name: Build jar

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-jar:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Build jar
        run: ./gradlew fatJar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Svg2VectorAndroid
          path: build/libs/*.jar

      - name: Clean Workflow Logs
        uses: igorjs/gh-actions-clean-workflow@v3
        with:
               token: ${{ secrets.TOKEN }}
               days_old: 0  
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install gitpython requests
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Svg2VectorAndroid
          path: artifacts/Svg2VectorAndroid.jar
      - name: Send notifications
        run: python send_notifications.py
        env:
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          TELEGRAM_CI_BOT_TOKEN: ${{ secrets.TELEGRAM_CI_BOT_TOKEN }}
          TELEGRAM_CI_CHANNEL_ID: ${{ secrets.TELEGRAM_CI_CHANNEL_ID }}
          ARTIFACT_DIRECTORY: artifacts/Svg2VectorAndroid.jar
          GITHUB_REF: ${{ github.ref }}
